replicaCount: 3

autoscaling:
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

pdb:
  minAvailable: 2

config:
  dbUrl: "jdbc:postgresql://REPLACE_WITH_PROD_RDS_ENDPOINT:5432/transactions"
  paymentProviderBaseUrl: "https://REPLACE_WITH_PROVIDER_URL"
  serverPort: "8080"

secretsManager:
  region: "us-east-1"
  secretArn: "REPLACE_WITH_SECRETS_MANAGER_ARN"

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "REPLACE_WITH_ACM_ARN"
    alb.ingress.kubernetes.io/wafv2-acl-arn: "REPLACE_WITH_WAF_ACL_ARN"
    external-dns.alpha.kubernetes.io/hostname: "transaction-api.example.com"
  hosts:
    - host: "transaction-api.example.com"
      paths:
        - path: /
          pathType: Prefix
