apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transaction-api.fullname" . }}-config
  labels:
    {{- include "transaction-api.labels" . | nindent 4 }}
data:
  DB_URL: {{ .Values.config.dbUrl | quote }}
  PAYMENT_PROVIDER_BASE_URL: {{ .Values.config.paymentProviderBaseUrl | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
