apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transaction-api.fullname" . }}
  labels:
    {{- include "transaction-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "transaction-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "transaction-api.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ include "transaction-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "transaction-api.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "transaction-api.fullname" . }}-config
                  key: DB_URL
            - name: PAYMENT_PROVIDER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "transaction-api.fullname" . }}-config
                  key: PAYMENT_PROVIDER_BASE_URL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "transaction-api.fullname" . }}-config
                  key: SERVER_PORT
            {{- if .Values.externalSecret.enabled }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "transaction-api.fullname" . }}-secret
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "transaction-api.fullname" . }}-secret
                  key: db-password
            - name: PAYMENT_PROVIDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "transaction-api.fullname" . }}-secret
                  key: payment-provider-api-key
            {{- end }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
