{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "transaction-api.fullname" . }}-secret
  labels:
    {{- include "transaction-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ include "transaction-api.fullname" . }}-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: db-username
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: db-username
    - secretKey: db-password
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: db-password
    - secretKey: payment-provider-api-key
      remoteRef:
        key: {{ .Values.externalSecret.remoteRef.key }}
        property: payment-provider-api-key
{{- end }}
