apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "transaction-api.fullname" . }}
  labels:
    {{- include "transaction-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "transaction-api.selectorLabels" . | nindent 6 }}
