{{- if .Values.secretsManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "transaction-api.fullname" . }}-aws-secrets
  labels:
    {{- include "transaction-api.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.secretsManager.region | quote }}
    objects: |
      - objectName: {{ .Values.secretsManager.secretArn | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "db-username"
            objectAlias: "spring.datasource.username"
          - path: "db-password"
            objectAlias: "spring.datasource.password"
          - path: "payment-provider-api-key"
            objectAlias: "payment-provider.api-key"
{{- end }}
